[project]
name = "fine-tuned-stranded"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.36",
    "strands-agents>=1.23.0",
    "strands-agents-tools>=0.2.19",
]
